import { Modal } from '../../../shared/components/Modal'

interface Props {
  open: boolean
  onClose: () => void
}

export function HelpModal({ open, onClose }: Props) {
  return (
    <Modal open={open} onClose={onClose} title="How to play Ladder">
      <p>
        Get from the start word to the target word by changing one letter at a
        time. Every word in your chain must be a real five-letter word.
      </p>
      <ul className="help-list">
        <li>
          Type a word and press Enter. If it&apos;s a valid one-letter change
          from the previous word, it joins the chain.
        </li>
        <li>
          You can take any path you like — but the goal is to reach the
          target in as few steps as possible. The puzzle shows the
          information-theoretic optimum so you have something to chase.
        </li>
        <li>
          <strong>Give up</strong> reveals the optimal path the BFS solver
          found.
        </li>
      </ul>
      <p className="help-footnote">
        The pair (start, target) is generated by an LLM and verified solvable
        by a BFS over the same valid-guess dictionary Purdle uses. The
        optimum is precomputed at puzzle-generation time.
      </p>
    </Modal>
  )
}
