import { Modal } from '../../../shared/components/Modal'

interface Props {
  open: boolean
  onClose: () => void
}

// Mini cell components — purely presentational, just to render visual
// examples inside the help modal. They reuse the live game's CSS classes
// so what the player sees here matches what they see while playing.
function ExampleRow({
  letters,
  variant,
  changedIdx,
}: {
  letters: string
  variant: 'start' | 'target' | 'chain' | 'input'
  changedIdx?: number
}) {
  return (
    <div className={`l-row l-row--${variant} help-ladder-row`}>
      {letters.split('').map((ch, i) => (
        <span
          key={i}
          className={
            'l-cell' +
            (variant === 'input' ? ' l-cell--input l-cell--filled' : '') +
            (changedIdx === i ? ' l-cell--changed' : '')
          }
        >
          {ch.toUpperCase()}
        </span>
      ))}
    </div>
  )
}

export function HelpModal({ open, onClose }: Props) {
  return (
    <Modal open={open} onClose={onClose} title="How to play Ladder">
      <p>
        Get from the <strong>start</strong> word to the <strong>target</strong>{' '}
        by changing one letter at a time. Every word in your chain must be a
        real five-letter word.
      </p>

      <h3 className="help-section">The board</h3>
      <p>
        The <strong>start</strong> word is shown as a green tile at the top —
        you begin here.
      </p>
      <ExampleRow letters="carve" variant="start" />
      <p>
        The <strong>target</strong> sits at the bottom with a dashed outline —
        that&apos;s where your chain has to end up.
      </p>
      <ExampleRow letters="whole" variant="target" />

      <h3 className="help-section">As you type</h3>
      <p>
        Type a five-letter word. The position that differs from the previous
        word lights up <strong>yellow</strong>. Exactly one yellow letter
        means it&apos;s a valid one-step move:
      </p>
      <ExampleRow letters="curve" variant="input" changedIdx={1} />
      <p>
        Press <kbd>Enter</kbd> to commit. The word joins the chain and the
        yellow letter stays so you can see what changed at each step.
      </p>
      <ExampleRow letters="curve" variant="chain" changedIdx={1} />

      <h3 className="help-section">Submission rules</h3>
      <ul className="help-list">
        <li>Exactly five letters, in the dictionary.</li>
        <li>Differs from your previous word by exactly one letter.</li>
        <li>Hasn&apos;t already appeared in your chain.</li>
      </ul>
      <p>
        The counter shows your current step count vs the BFS-optimal — try to
        match it. <strong>Give up</strong> reveals the optimal path so you can
        compare.
      </p>

      <p className="help-footnote">
        The (start, target) pair is generated by an LLM and verified solvable
        by a BFS over the same valid-guess dictionary Purdle uses. The
        optimum is precomputed at puzzle-generation time.
      </p>
    </Modal>
  )
}
