import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      // Precache the SPA shell + 404 fallback. The other static assets
      // (puzzle JSONs, dictionary, synonym graph) are handled at runtime
      // because they're large and update independently.
      includeAssets: ['favicon.svg', 'favicon.ico', 'apple-touch-icon-180x180.png'],
      manifest: {
        name: 'Purdle — daily LLM word puzzles',
        short_name: 'Purdle',
        description:
          'Four daily word puzzles — Purdle, Quartet, Ladder, Synonymy — generated by an automated LLM + ML pipeline.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        background_color: '#ffffff',
        theme_color: '#6aaa64',
        orientation: 'portrait',
        icons: [
          { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
          { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          {
            src: 'maskable-icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Files Workbox precaches at SW install time. Includes hashed JS/CSS
        // emitted by Vite. Keep the dictionary out of precache (200 KB) —
        // it's loaded lazily and runtime-cached on first use.
        globPatterns: ['**/*.{js,css,html,svg,ico,png}'],
        // The dictionary + synonym graph + puzzle JSONs aren't precached.
        // Runtime caching strategies cover them:
        runtimeCaching: [
          {
            // Today's puzzle: always try network first so a player who's
            // online after midnight UTC sees the new puzzle immediately.
            // Falls back to cache when offline.
            urlPattern: /\/puzzles\/.+\.json$/,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'purdle-puzzles',
              networkTimeoutSeconds: 4,
              expiration: {
                maxEntries: 60,
                maxAgeSeconds: 60 * 60 * 24 * 60, // 60 days
              },
            },
          },
          {
            // Static word lists: the synonym graph (~50 KB) and dictionary
            // (~200 KB) only change when we rebuild them. Cache-first is
            // safe — Workbox revalidates on update.
            urlPattern: /\/words\/.+\.(?:json|txt)$/,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'purdle-words',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
              },
            },
          },
        ],
        // Don't intercept Supabase REST calls — those need to hit the
        // network every time so stats sync correctly.
        navigateFallbackDenylist: [/^\/api\//],
      },
      devOptions: {
        // Don't register the SW in `vite dev` — it caches dev-mode artifacts
        // that go stale on reload. PWA features only kick in for prod builds.
        enabled: false,
      },
    }),
  ],
  // Custom domain at purdle.app — Pages serves from root, not /Purdle/.
  base: '/',
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/test-setup.ts'],
  },
})
