import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import type { Puzzle } from '../games/wordle/types'
import { DEFAULT_LANGUAGE } from '../games/wordle/types'
import { todayUTC } from '../shared/lib/date'

interface ManifestResponse {
  dates: string[]
}

const PUZZLES_BASE = `${import.meta.env.BASE_URL}puzzles/wordle/${DEFAULT_LANGUAGE}/`

type LoadState =
  | { status: 'loading' }
  | { status: 'ready'; puzzles: Puzzle[] }
  | { status: 'error'; message: string }

async function fetchManifest(): Promise<string[]> {
  const r = await fetch(PUZZLES_BASE + 'index.json', { cache: 'no-cache' })
  if (!r.ok) throw new Error(`manifest ${r.status}`)
  const m = (await r.json()) as ManifestResponse
  return m.dates ?? []
}

async function fetchPuzzle(date: string): Promise<Puzzle | null> {
  try {
    const r = await fetch(PUZZLES_BASE + date + '.json', { cache: 'no-cache' })
    if (!r.ok) return null
    return (await r.json()) as Puzzle
  } catch {
    return null
  }
}

export function ArchivePage() {
  const [state, setState] = useState<LoadState>({ status: 'loading' })

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const dates = await fetchManifest()
        const today = todayUTC()
        // Newest first; exclude today (still in play, would spoil it).
        const past = dates.filter((d) => d < today).reverse()
        const results = await Promise.all(past.map(fetchPuzzle))
        if (cancelled) return
        const puzzles = results.filter((p): p is Puzzle => p !== null)
        setState({ status: 'ready', puzzles })
      } catch (e) {
        if (cancelled) return
        setState({
          status: 'error',
          message: e instanceof Error ? e.message : 'Unknown error',
        })
      }
    })()
    return () => {
      cancelled = true
    }
  }, [])

  return (
    <main className="archive">
      <div className="archive-header">
        <Link to="/wordle" className="archive-back">
          &larr; Back to today&apos;s puzzle
        </Link>
        <h2 className="archive-title">Past puzzles</h2>
        <p className="archive-sub">
          Every word below was generated by the automated LLM + ML pipeline.
          Click <strong>Play</strong> to attempt one without affecting your
          stats; click <strong>Reveal</strong> if you just want to see the
          word and its etymology.
        </p>
      </div>

      {state.status === 'loading' && (
        <div className="archive-empty">Loading…</div>
      )}

      {state.status === 'error' && (
        <div className="archive-empty">
          Couldn&apos;t load past puzzles: {state.message}
        </div>
      )}

      {state.status === 'ready' && state.puzzles.length === 0 && (
        <div className="archive-empty">No past puzzles yet — check back tomorrow.</div>
      )}

      {state.status === 'ready' && state.puzzles.length > 0 && (
        <ul className="archive-list">
          {state.puzzles.map((p) => (
            <ArchiveCard key={p.date} puzzle={p} />
          ))}
        </ul>
      )}
    </main>
  )
}

function ArchiveCard({ puzzle }: { puzzle: Puzzle }) {
  const [revealed, setRevealed] = useState(false)

  return (
    <li className="archive-card">
      <div className="archive-card-row">
        <time className="archive-date" dateTime={puzzle.date}>
          {formatDate(puzzle.date)}
        </time>
        <div className="archive-meta">
          {puzzle.difficulty != null && (
            <span className="archive-tag" title="Difficulty (1–5)">
              ★ {puzzle.difficulty}
            </span>
          )}
          <span
            className={
              'archive-tag archive-tag--source' +
              (puzzle.generated_by === 'fallback' ? ' archive-tag--fallback' : '')
            }
            title="Generator"
          >
            {puzzle.generated_by ?? 'unknown'}
          </span>
        </div>
      </div>

      <div className="archive-actions">
        <Link to={`/wordle/archive/${puzzle.date}`} className="archive-play-btn">
          Play
        </Link>
        <button
          type="button"
          className="archive-reveal-btn"
          onClick={() => setRevealed((v) => !v)}
          aria-expanded={revealed}
        >
          {revealed ? 'Hide' : 'Reveal'}
        </button>
      </div>

      {revealed && (
        <div className="archive-reveal-body">
          <div className="archive-card-row">
            <span className="archive-reveal-label">Solution</span>
            <span className="archive-solution">
              {puzzle.solution.toUpperCase()}
            </span>
          </div>
          {puzzle.theme && (
            <div className="archive-card-row">
              <span className="archive-reveal-label">Theme</span>
              <span>{puzzle.theme}</span>
            </div>
          )}
          {puzzle.etymology && (
            <p className="archive-etymology">{puzzle.etymology}</p>
          )}
        </div>
      )}
    </li>
  )
}

function formatDate(iso: string): string {
  const [y, m, d] = iso.split('-').map(Number)
  const months = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ]
  return `${months[m - 1]} ${d}, ${y}`
}
