import { Link } from 'react-router-dom'
import { todayUTC } from '../shared/lib/date'

export function Home() {
  return (
    <main className="home">
      <div className="home-hero">
        <span className="home-eyebrow">{prettyDate(todayUTC())}</span>
        <h2 className="home-title">
          A daily word puzzle generated by a machine.
        </h2>
        <p className="home-sub">
          Every Purdle puzzle is the output of an automated pipeline — a Gemini
          model proposes a word; classical ML validates it for novelty, frequency,
          and profanity; the result ships to your browser. No human curates the
          word list, no human picks today&apos;s answer.
        </p>
      </div>

      <div className="home-games">
        <Link to="/play" className="home-card home-card--primary">
          <div className="home-card-body">
            <div className="home-card-title">Purdle</div>
            <div className="home-card-meta">Today&apos;s puzzle · 6 guesses</div>
          </div>
          <span className="home-card-arrow" aria-hidden>
            →
          </span>
        </Link>

        <Link to="/quartet" className="home-card home-card--primary home-card--quartet">
          <div className="home-card-body">
            <div className="home-card-title">Quartet</div>
            <div className="home-card-meta">
              Today&apos;s puzzle · 16 words, 4 groups
            </div>
          </div>
          <span className="home-card-arrow" aria-hidden>
            →
          </span>
        </Link>

        <Link to="/ladder" className="home-card home-card--primary home-card--ladder">
          <div className="home-card-body">
            <div className="home-card-title">Ladder</div>
            <div className="home-card-meta">
              Today&apos;s puzzle · chain start → end, one letter at a time
            </div>
          </div>
          <span className="home-card-arrow" aria-hidden>
            →
          </span>
        </Link>

        <Link to="/play/archive" className="home-card">
          <div className="home-card-body">
            <div className="home-card-title">Purdle archive</div>
            <div className="home-card-meta">Past Purdle puzzles · play any day</div>
          </div>
          <span className="home-card-arrow" aria-hidden>
            →
          </span>
        </Link>

        <Link to="/quartet/archive" className="home-card">
          <div className="home-card-body">
            <div className="home-card-title">Quartet archive</div>
            <div className="home-card-meta">Past Quartet puzzles · play any day</div>
          </div>
          <span className="home-card-arrow" aria-hidden>
            →
          </span>
        </Link>

        <Link to="/ladder/archive" className="home-card">
          <div className="home-card-body">
            <div className="home-card-title">Ladder archive</div>
            <div className="home-card-meta">Past Ladder puzzles · play any day</div>
          </div>
          <span className="home-card-arrow" aria-hidden>
            →
          </span>
        </Link>
      </div>

      <p className="home-foot">
        Free to play and free to host on GitHub Pages — see the{' '}
        <a
          href="https://github.com/pedromussi1/Purdle"
          target="_blank"
          rel="noreferrer"
        >
          source on GitHub
        </a>{' '}
        for the architecture writeup.
      </p>
    </main>
  )
}

function prettyDate(iso: string): string {
  const [y, m, d] = iso.split('-').map(Number)
  const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ]
  return `${months[m - 1]} ${d}, ${y}`
}
