import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { todayUTC } from '../shared/lib/date'
import {
  readTodayStatus,
  type TodayStatus,
  type TodayStatusMap,
} from './lib/todayStatus'

export function Home() {
  const [status, setStatus] = useState<TodayStatusMap>({})

  useEffect(() => {
    setStatus(readTodayStatus())
    const onFocus = () => setStatus(readTodayStatus())
    window.addEventListener('focus', onFocus)
    document.addEventListener('visibilitychange', onFocus)
    return () => {
      window.removeEventListener('focus', onFocus)
      document.removeEventListener('visibilitychange', onFocus)
    }
  }, [])

  return (
    <main className="home">
      <div className="home-hero">
        <span className="home-eyebrow">{prettyDate(todayUTC())}</span>
        <h2 className="home-title">
          A daily word puzzle generated by a machine.
        </h2>
        <p className="home-sub">
          Every Purdle puzzle is the output of an automated pipeline — a Gemini
          model proposes a word; classical ML validates it for novelty, frequency,
          and profanity; the result ships to your browser. No human curates the
          word list, no human picks today&apos;s answer.
        </p>
      </div>

      <div className="home-games">
        <GameCard
          to="/play"
          modifier="home-card--primary"
          title="Purdle"
          meta="Today's puzzle · 6 guesses"
          status={status.purdle}
        />
        <GameCard
          to="/quartet"
          modifier="home-card--primary home-card--quartet"
          title="Quartet"
          meta="Today's puzzle · 16 words, 4 groups"
          status={status.quartet}
        />
        <GameCard
          to="/ladder"
          modifier="home-card--primary home-card--ladder"
          title="Ladder"
          meta="Today's puzzle · chain start → end, one letter at a time"
          status={status.ladder}
        />
        <GameCard
          to="/synonymy"
          modifier="home-card--primary home-card--synonymy"
          title="Synonymy"
          meta="Today's puzzle · chain start → end through synonyms"
          status={status.synonymy}
        />

        <ArchiveCard to="/play/archive" title="Purdle archive" meta="Past Purdle puzzles · play any day" />
        <ArchiveCard to="/quartet/archive" title="Quartet archive" meta="Past Quartet puzzles · play any day" />
        <ArchiveCard to="/ladder/archive" title="Ladder archive" meta="Past Ladder puzzles · play any day" />
        <ArchiveCard to="/synonymy/archive" title="Synonymy archive" meta="Past Synonymy puzzles · play any day" />
      </div>

      <p className="home-foot">
        Free to play and free to host on GitHub Pages — see the{' '}
        <a
          href="https://github.com/pedromussi1/Purdle"
          target="_blank"
          rel="noreferrer"
        >
          source on GitHub
        </a>{' '}
        for the architecture writeup.
      </p>
    </main>
  )
}

interface GameCardProps {
  to: string
  modifier: string
  title: string
  meta: string
  status: TodayStatus | undefined
}

function GameCard({ to, modifier, title, meta, status }: GameCardProps) {
  return (
    <Link to={to} className={`home-card ${modifier}`}>
      <div className="home-card-body">
        <div className="home-card-title">{title}</div>
        <div className="home-card-meta">{meta}</div>
        {status && (
          <div className={`home-card-status home-card-status--${status.state}`}>
            {status.detail}
          </div>
        )}
      </div>
      <span className="home-card-arrow" aria-hidden>
        →
      </span>
    </Link>
  )
}

function ArchiveCard({ to, title, meta }: { to: string; title: string; meta: string }) {
  return (
    <Link to={to} className="home-card">
      <div className="home-card-body">
        <div className="home-card-title">{title}</div>
        <div className="home-card-meta">{meta}</div>
      </div>
      <span className="home-card-arrow" aria-hidden>
        →
      </span>
    </Link>
  )
}

function prettyDate(iso: string): string {
  const [y, m, d] = iso.split('-').map(Number)
  const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ]
  return `${months[m - 1]} ${d}, ${y}`
}
