import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { fetchManifest, fetchPuzzle } from '../games/quartet/hooks/usePuzzle'
import type { QuartetPuzzle } from '../games/quartet/types'
import { todayUTC } from '../shared/lib/date'

type LoadState =
  | { status: 'loading' }
  | { status: 'ready'; puzzles: QuartetPuzzle[] }
  | { status: 'error'; message: string }

export function QuartetArchive() {
  const [state, setState] = useState<LoadState>({ status: 'loading' })

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const manifest = await fetchManifest()
        const dates = manifest?.dates ?? []
        const today = todayUTC()
        const past = dates.filter((d) => d < today).reverse()
        const results = await Promise.all(past.map(fetchPuzzle))
        if (cancelled) return
        const puzzles = results.filter((p): p is QuartetPuzzle => p !== null)
        setState({ status: 'ready', puzzles })
      } catch (e) {
        if (cancelled) return
        setState({
          status: 'error',
          message: e instanceof Error ? e.message : 'Unknown error',
        })
      }
    })()
    return () => {
      cancelled = true
    }
  }, [])

  return (
    <main className="archive">
      <div className="archive-header">
        <Link to="/quartet" className="archive-back">
          &larr; Back to today&apos;s Quartet
        </Link>
        <h2 className="archive-title">Past Quartets</h2>
        <p className="archive-sub">
          Every puzzle below was generated by the LLM + embedding-clustering
          pipeline. <strong>Play</strong> opens an ephemeral replay (no impact
          on your stats); <strong>Reveal</strong> shows the four themes inline.
        </p>
      </div>

      {state.status === 'loading' && (
        <div className="archive-empty">Loading…</div>
      )}

      {state.status === 'error' && (
        <div className="archive-empty">
          Couldn&apos;t load past Quartets: {state.message}
        </div>
      )}

      {state.status === 'ready' && state.puzzles.length === 0 && (
        <div className="archive-empty">No past puzzles yet — check back tomorrow.</div>
      )}

      {state.status === 'ready' && state.puzzles.length > 0 && (
        <ul className="archive-list">
          {state.puzzles.map((p) => (
            <ArchiveCard key={p.date} puzzle={p} />
          ))}
        </ul>
      )}
    </main>
  )
}

function ArchiveCard({ puzzle }: { puzzle: QuartetPuzzle }) {
  const [revealed, setRevealed] = useState(false)
  return (
    <li className="archive-card">
      <div className="archive-card-row">
        <time className="archive-date" dateTime={puzzle.date}>
          {formatDate(puzzle.date)}
        </time>
        <div className="archive-meta">
          <span
            className={
              'archive-tag archive-tag--source' +
              (puzzle.generated_by === 'fallback'
                ? ' archive-tag--fallback'
                : '')
            }
            title="Generator"
          >
            {puzzle.generated_by ?? 'unknown'}
          </span>
        </div>
      </div>

      <div className="archive-actions">
        <Link to={`/quartet/archive/${puzzle.date}`} className="archive-play-btn">
          Play
        </Link>
        <button
          type="button"
          className="archive-reveal-btn"
          onClick={() => setRevealed((v) => !v)}
          aria-expanded={revealed}
        >
          {revealed ? 'Hide' : 'Reveal'}
        </button>
      </div>

      {revealed && (
        <div className="archive-reveal-body">
          {[...puzzle.groups]
            .sort((a, b) => a.tier - b.tier)
            .map((g, i) => (
              <div className={`q-solved q-solved--tier-${g.tier}`} key={i}>
                <div className="q-solved-theme">{g.theme.toUpperCase()}</div>
                <div className="q-solved-words">
                  {g.words.join(', ').toUpperCase()}
                </div>
              </div>
            ))}
        </div>
      )}
    </li>
  )
}

function formatDate(iso: string): string {
  const [y, m, d] = iso.split('-').map(Number)
  const months = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ]
  return `${months[m - 1]} ${d}, ${y}`
}
