import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { fetchManifest, fetchPuzzle } from '../games/synonymy/hooks/usePuzzle'
import type { SynonymyPuzzle } from '../games/synonymy/types'
import { todayUTC } from '../shared/lib/date'

type LoadState =
  | { status: 'loading' }
  | { status: 'ready'; puzzles: SynonymyPuzzle[] }
  | { status: 'error'; message: string }

export function SynonymyArchive() {
  const [state, setState] = useState<LoadState>({ status: 'loading' })

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const manifest = await fetchManifest()
        const dates = manifest?.dates ?? []
        const today = todayUTC()
        const past = dates.filter((d) => d < today).reverse()
        const results = await Promise.all(past.map(fetchPuzzle))
        if (cancelled) return
        const puzzles = results.filter((p): p is SynonymyPuzzle => p !== null)
        setState({ status: 'ready', puzzles })
      } catch (e) {
        if (cancelled) return
        setState({
          status: 'error',
          message: e instanceof Error ? e.message : 'Unknown error',
        })
      }
    })()
    return () => {
      cancelled = true
    }
  }, [])

  return (
    <main className="archive">
      <div className="archive-header">
        <Link to="/synonymy" className="archive-back">
          &larr; Back to today&apos;s synonymy
        </Link>
        <h2 className="archive-title">Past synonymies</h2>
        <p className="archive-sub">
          Each pair was generated by the LLM + embedding-graph pipeline.
          <strong> Play</strong> opens an ephemeral replay (no impact on
          your stats); <strong>Reveal</strong> shows the optimal path
          inline.
        </p>
      </div>

      {state.status === 'loading' && (
        <div className="archive-empty">Loading…</div>
      )}
      {state.status === 'error' && (
        <div className="archive-empty">
          Couldn&apos;t load past synonymies: {state.message}
        </div>
      )}
      {state.status === 'ready' && state.puzzles.length === 0 && (
        <div className="archive-empty">No past puzzles yet — check back tomorrow.</div>
      )}
      {state.status === 'ready' && state.puzzles.length > 0 && (
        <ul className="archive-list">
          {state.puzzles.map((p) => (
            <ArchiveCard key={p.date} puzzle={p} />
          ))}
        </ul>
      )}
    </main>
  )
}

function ArchiveCard({ puzzle }: { puzzle: SynonymyPuzzle }) {
  const [revealed, setRevealed] = useState(false)
  return (
    <li className="archive-card">
      <div className="archive-card-row">
        <time className="archive-date" dateTime={puzzle.date}>
          {formatDate(puzzle.date)}
        </time>
        <div className="archive-meta">
          <span className="archive-tag" title="Optimal step count">
            {puzzle.optimal_steps} steps
          </span>
          <span
            className={
              'archive-tag archive-tag--source' +
              (puzzle.generated_by === 'fallback' ? ' archive-tag--fallback' : '')
            }
            title="Generator"
          >
            {puzzle.generated_by ?? 'unknown'}
          </span>
        </div>
      </div>

      <div className="archive-actions">
        <Link to={`/synonymy/archive/${puzzle.date}`} className="archive-play-btn">
          Play
        </Link>
        <button
          type="button"
          className="archive-reveal-btn"
          onClick={() => setRevealed((v) => !v)}
          aria-expanded={revealed}
        >
          {revealed ? 'Hide' : 'Reveal'}
        </button>
      </div>

      {revealed && (
        <div className="archive-reveal-body">
          <div className="archive-card-row">
            <span className="archive-reveal-label">Pair</span>
            <span className="archive-solution">
              {puzzle.start.toUpperCase()} → {puzzle.end.toUpperCase()}
            </span>
          </div>
          <div className="archive-card-row">
            <span className="archive-reveal-label">Optimal path</span>
            <span style={{ fontFamily: 'ui-monospace, Consolas, monospace' }}>
              {puzzle.optimal_path.map((w) => w.toUpperCase()).join(' → ')}
            </span>
          </div>
        </div>
      )}
    </li>
  )
}

function formatDate(iso: string): string {
  const [y, m, d] = iso.split('-').map(Number)
  const months = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ]
  return `${months[m - 1]} ${d}, ${y}`
}
